import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import NavBar from '@/components/NavBar';
import Providers from '@/components/Providers';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='h-full'>
      {/*cn() helper function can invoke ui library */}
      <body
        className={cn(
          'relative h-full font-sans antialiased ',
          inter.className
        )}
        suppressHydrationWarning={true}
      >
        <main className='relative flex flex-col min-h-screen'>
          {/* Here Provider is used to make accessable trpc and react-query to all components */}
          <Providers>
            <NavBar />
            <div className='flex-grow flex-1'>{children}</div>
          </Providers>
        </main>
        <Toaster position='top-center' richColors/>
      </body>
    </html>
  );
}


// To avoid Warning: Extra attributes from the server: data-new-gr-c-s-check-loaded,data-gr-ext-installed
// use suppressHydrationWarning={true} in <body> element